openapi: 3.0.3
info:
  title: Online Banking API
  description: >
    API for managing bank accounts, fund transfers, and transaction history.
  version: 1.0.0
  contact:
    name: Support Team
    email: support@bankapi.com

servers:
  - url: http://api.souravbank.com/v1
    description: Production Server

security:
  - BearerAuth: []

paths:
  /auth/login:
    post:
      summary: User login
      description: >
        Authenticates user and returns JWT token.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
              required: [username, password]
      responses:
        "200":
          description: Successful login
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
        "401":
          description: Unauthorized (invalid credentials)

  /auth/logout:
    post:
      summary: User logout
      description: >
        Logs out the user by invalidating the JWT token.
      responses:
        "200":
          description: Successful logout

  /accounts/{id}:
    get:
      summary: Retrieve account details
      description: >
        Gets details of a specific account by ID.
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Account details retrieved
          content:
            application/json:
              schema:
                type: object
                properties:
                  accountId:
                    type: string
                  balance:
                    type: number
                    format: float
                  accountType:
                    type: string
                  email:
                    type: string
                  phone:
                    type: string
        "404":
          description: Account not found

    put:
      summary: Update account information
      description: >
        Updates account details such as contact information.
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                phone:
                  type: string
      responses:
        "200":
          description: Account updated successfully
        "400":
          description: Invalid input

  /transactions/transfer:
    post:
      summary: Initiate a fund transfer
      description: >
        Transfers funds from one account to another.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                fromAccount:
                  type: string
                toAccount:
                  type: string
                amount:
                  type: number
                  format: float
              required: [fromAccount, toAccount, amount]
      responses:
        "200":
          description: Transfer successful
        "400":
          description: Invalid transaction request
        "403":
          description: Insufficient funds

  /transactions/history:
    get:
      summary: Retrieve transaction history
      description: >
        Fetches the transaction history of the authenticated user.
      responses:
        "200":
          description: Transaction history retrieved
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    transactionId:
                      type: string
                    amount:
                      type: number
                      format: float
                    type:
                      type: string
                      enum: [debit, credit]
                    timestamp:
                      type: string
                      format: date-time

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  responses:
    ErrorResponse:
      description: Error response
      content:
        application/json:
          schema:
            type: object
            properties:
              error:
                type: string
              message:
                type: string